services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SUI_NETWORK: testnet
        NEXT_PUBLIC_CETUS_SWAP_PACKAGE_ID: 0x3165544e38f9baf1a897d2660a2a545f9634862417444c63c9f401da8b67a331
        NEXT_PUBLIC_GOOGLE_CLIENT_ID: 96407708019-pkjplel118bu7v1uncv6ji0g1ms7bb3g.apps.googleusercontent.com
        NEXT_PUBLIC_APP_URL: http://localhost:3000
    container_name: sui-hack-frontend
    ports:
      - "${PORT:-3001}:${PORT:-3001}"
    environment:
      - PORT=${PORT:-3001}
      - HOSTNAME=0.0.0.0
    restart: always
